# Generated by Django 2.2.1 on 2022-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('amount_price', models.IntegerField(verbose_name='商品价格')),
            ],
        ),
        migrations.CreateModel(
            name='CountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15, verbose_name='日期')),
                ('openid', models.CharField(max_length=40, verbose_name='用户id')),
                ('is_login', models.IntegerField(default=0, verbose_name='是否登录')),
                ('is_make', models.IntegerField(default=0, verbose_name='是否生成视频')),
                ('is_payment', models.IntegerField(default=0, verbose_name='是否付款')),
                ('date_stamp', models.DateTimeField(verbose_name='日期时间戳')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入数据时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=2550, null=True, verbose_name='用户头像')),
                ('gender', models.IntegerField(blank=True, null=True, verbose_name='用户性别')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户所在国家')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户所在省份')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户所在城市')),
                ('language', models.CharField(blank=True, max_length=255, null=True, verbose_name='所用的语言')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入数据时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新数据时间')),
                ('openid', models.CharField(max_length=255, verbose_name='用户id')),
                ('user_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='临时key')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('openid', models.CharField(max_length=255, verbose_name='用户id')),
                ('picture_url', models.CharField(blank=True, max_length=2550, null=True, verbose_name='视频图像地址')),
                ('video_url', models.CharField(blank=True, max_length=2550, null=True, verbose_name='视频地址')),
                ('generate_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频生成时间')),
                ('invalid_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频失效时间')),
                ('read_state', models.IntegerField(default=1, verbose_name='视频状态')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入数据时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新数据时间')),
                ('secret_key', models.CharField(blank=True, max_length=20, null=True, verbose_name='秘钥')),
                ('generate_stamp', models.DateTimeField(blank=True, null=True, verbose_name='视频生成时间戳')),
                ('video_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='视频类型')),
                ('pay_status', models.IntegerField(default=0, verbose_name='视频支付状态')),
            ],
        ),
    ]
