# Generated by Django 2.2.1 on 2022-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='is_del',
            field=models.IntegerField(default=0, verbose_name='视频支付状态'),
        ),
    ]
